apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: centos-stream9-qmpcx3e48tel82ch
      vm.kubevirt.io/template: centos-stream9-desktop-tiny
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: centos-stream9-qmpcx3e48tel82ch
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: centos-stream9-qmpcx3e48tel82ch
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: tiny
          vm.kubevirt.io/os: centos-stream9
          vm.kubevirt.io/workload: desktop
        labels:
          kubevirt.io/domain: centos-stream9-qmpcx3e48tel82ch
          kubevirt.io/size: tiny
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          resources:
            requests:
              memory: 1.5Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: centos-stream9-qmpcx3e48tel82ch
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: swgp-8jc4-jrcr
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
