apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 536870912
          }
        ]
    labels:
      app: centos6-6k557y0jl0t13jdh
      vm.kubevirt.io/template: centos6-server-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: centos6-6k557y0jl0t13jdh
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: centos6-6k557y0jl0t13jdh
      spec:
        sourceRef:
          kind: DataSource
          name: centos6
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: centos6
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: centos6-6k557y0jl0t13jdh
          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
            useVirtioTransitional: true
          resources:
            requests:
              memory: 2Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: centos6-6k557y0jl0t13jdh
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: 2pbf-5kuv-he4p
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
