apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1073741824
          }
        ]
    labels:
      app: fedora-ao1jn238a4pn0d0x
      vm.kubevirt.io/template: fedora-desktop-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: fedora-ao1jn238a4pn0d0x
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora-ao1jn238a4pn0d0x
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: fedora
          vm.kubevirt.io/workload: desktop
        labels:
          kubevirt.io/domain: fedora-ao1jn238a4pn0d0x
          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 2Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: fedora-ao1jn238a4pn0d0x
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: 0ukg-jshc-i0fu
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
