apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1073741824
          }
        ]
    labels:
      app: opensuse-ao81ud731dyefp1i
      vm.kubevirt.io/template: opensuse-server-large
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: opensuse-ao81ud731dyefp1i
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: opensuse-ao81ud731dyefp1i
      spec:
        sourceRef:
          kind: DataSource
          name: opensuse
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: large
          vm.kubevirt.io/os: opensuse
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: opensuse-ao81ud731dyefp1i
          kubevirt.io/size: large
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 2
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          resources:
            requests:
              memory: 8Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: opensuse-ao81ud731dyefp1i
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: opensuse
              password: 60m7-b7lu-5a4o
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
