apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: rhel9-fuknkm4fpbr48ql1
      vm.kubevirt.io/template: rhel9-server-large
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: rhel9-fuknkm4fpbr48ql1
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-fuknkm4fpbr48ql1
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: large
          vm.kubevirt.io/os: rhel9
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: rhel9-fuknkm4fpbr48ql1
          kubevirt.io/size: large
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 2
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 8Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: rhel9-fuknkm4fpbr48ql1
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: jcc7-f3ql-1omo
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
