apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 2147483648
          }
        ]
    labels:
      app: ubuntu-csccepewyqx71o8n
      vm.kubevirt.io/template: ubuntu-desktop-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: devel
    name: ubuntu-csccepewyqx71o8n
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ubuntu-csccepewyqx71o8n
      spec:
        sourceRef:
          kind: DataSource
          name: ubuntu
          namespace: kubevirt-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: ubuntu
          vm.kubevirt.io/workload: desktop
        labels:
          kubevirt.io/domain: ubuntu-csccepewyqx71o8n
          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          resources:
            requests:
              memory: 3Gi
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: ubuntu-csccepewyqx71o8n
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: ubuntu
              password: wsd8-ofvd-6qj2
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
