apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fedora-highperformance-medium
  annotations:
    openshift.io/display-name: "Fedora VM"
    description: >-
      Template for Fedora Linux 37 VM or newer.
      A PVC with the Fedora disk image must be available.
    tags: "hidden,kubevirt,virtualmachine,fedora"
    iconClass: "icon-fedora"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/kubevirt/common-templates"
    openshift.io/support-url: "https://github.com/kubevirt/common-templates/issues"
    template.openshift.io/bindable: "false"
    template.kubevirt.io/version: v1alpha1
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/containerdisks: |
      quay.io/containerdisks/fedora:latest
      quay.io/containerdisks/fedora:37
      quay.io/containerdisks/fedora:38
    template.kubevirt.io/images: |
      https://dl.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.qcow2
      https://dl.fedoraproject.org/pub/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.qcow2
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.resources.requests.memory
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    name.os.template.kubevirt.io/fedora37: Fedora Linux 37 or higher
    name.os.template.kubevirt.io/fedora38: Fedora Linux 37 or higher
  labels:
    os.template.kubevirt.io/fedora37: "true"
    os.template.kubevirt.io/fedora38: "true"
    workload.template.kubevirt.io/highperformance: "true"
    flavor.template.kubevirt.io/medium: "true"
    template.kubevirt.io/type: "base"
    template.kubevirt.io/version: "devel"
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      vm.kubevirt.io/template: fedora-highperformance-medium
      vm.kubevirt.io/template.version: "devel"
      vm.kubevirt.io/template.revision: "1"
      app: ${NAME}
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1073741824
          }
        ]
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ${NAME}
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
        sourceRef:
          kind: DataSource
          name: ${DATA_SOURCE_NAME}
          namespace: ${DATA_SOURCE_NAMESPACE}
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: "fedora"
          vm.kubevirt.io/workload: "highperformance"
          vm.kubevirt.io/flavor: "medium"
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: medium
      spec:
        domain:
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          ioThreadsPolicy: shared
          cpu:
            sockets: 1
            cores: 1
            threads: 1
            dedicatedCpuPlacement: True
            isolateEmulatorThread: True
          resources:
            requests:
              memory: 4Gi
          devices:
            rng: {}
            networkInterfaceMultiqueue: true
            disks:
            - disk:
                bus: virtio
              name: rootdisk
              dedicatedIOThread: true
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
              model: virtio
        terminationGracePeriodSeconds: 180
        networks:
        - name: default
          pod: {}
        volumes:
        - dataVolume:
            name: ${NAME}
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: ${CLOUD_USER_PASSWORD}
              chpasswd: { expire: False }
          name: cloudinitdisk
parameters:
- description: VM name
  from: 'fedora-[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: DATA_SOURCE_NAME
  description: Name of the DataSource to clone
  value: 'fedora'
- name: DATA_SOURCE_NAMESPACE
  description: Namespace of the DataSource
  value: kubevirt-os-images
- description: Randomized password for the cloud-init user fedora
  from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
  generate: expression
  name: CLOUD_USER_PASSWORD
